# Generated by Django 4.2.7 on 2024-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, default=''),
        ),
    ]
