# Generated by Django 4.2.7 on 2024-05-08 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0036_merge_20240424_1445"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="approval_minimum",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum approval percentage required for the poll to pass",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="finalization_period",
            field=models.DurationField(
                blank=True,
                help_text="Time period after the poll has ended before the result is finalized",
                null=True,
            ),
        ),
    ]
