# Generated by Django 4.2.7 on 2024-05-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0037_poll_approval_minimum_poll_finalization_period"),
        ("poll", "0037_poll_parent_alter_poll_poll_type"),
    ]

    operations = []
