# Generated by Django 4.2.7 on 2024-06-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0037_alter_pollpredictionbet_blockchain_id'),
        ('poll', '0037_poll_parent_alter_poll_poll_type'),
    ]

    operations = [
    ]
