# Generated by Django 4.2.7 on 2024-05-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0038_merge_20240514_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="finalization_period_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the finalization period started",
                null=True,
            ),
        ),
    ]
