# Generated by Django 4.2.7 on 2024-06-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0038_merge_20240612_1557'),
        ('poll', '0042_rename_finalization_period_start_poll_finalization_period_start_date'),
    ]

    operations = [
    ]
