# Generated by Django 4.2.7 on 2024-06-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0038_pollphasetemplate_and_more'),
        ('poll', '0043_merge_20240613_1136'),
    ]

    operations = [
    ]
