# Generated by Django 4.2.7 on 2024-11-27 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import flowback.decidables.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=16)),
                ('link', models.CharField(blank=True, default='', max_length=512)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[flowback.decidables.validators.allowed_image_extensions])),
            ],
        ),
        migrations.CreateModel(
            name='Decidable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('state', models.CharField(blank=True, choices=[('not_started', 'Not started'), ('open', 'Open'), ('closed', 'Closed')], default='not_started', max_length=32)),
                ('is_container', models.BooleanField(default=False)),
                ('decidable_type', models.CharField(choices=[('poll', 'Poll'), ('aspect', 'Aspect Poll'), ('reason', 'Reason Poll'), ('linkfile', 'Link File Poll'), ('vote', 'Vote'), ('challenge', 'Challenge'), ('election', 'Election')], max_length=256)),
                ('voting_type', models.CharField(choices=[('score', 'Score'), ('percentage', 'Percentage'), ('approval', 'Approval'), ('number', 'Number'), ('rating', 'Rating')], default='rating', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('has_tags_flag', models.BooleanField(blank=True, default=False)),
                ('allow_multiple_tags_flag', models.BooleanField(blank=True, default=False)),
                ('members_can_add_options', models.BooleanField(default=False)),
                ('quorum', models.IntegerField(default=51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('approval_minimum', models.PositiveIntegerField(default=51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('finalization_period', models.PositiveIntegerField(default=3, help_text='Finalization period in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('has_winners', models.BooleanField(blank=True, default=False)),
                ('num_winners', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecidableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDecidableAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDecidableOptionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
                ('quorum', models.IntegerField(blank=True, default=0)),
                ('approval', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupUserDecidableOptionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('decidables', models.ManyToManyField(blank=True, related_name='options', through='decidables.DecidableOption', to='decidables.decidable')),
                ('root_decidable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendent_options', to='decidables.decidable')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupUserDecidableVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
                ('group_decidable_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_decidable_vote', to='decidables.groupdecidableaccess')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
