# Generated by Django 4.2.7 on 2024-10-08 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import flowback.decidables.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0039_group_is_hub_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decidable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('state', models.CharField(blank=True, choices=[('not_started', 'Not started'), ('open', 'Open'), ('closed', 'Closed')], default='not_started', max_length=32)),
                ('is_container', models.BooleanField(default=False)),
                ('decidable_type', models.CharField(choices=[('poll', 'Poll'), ('reasonpoll', 'Reason Poll'), ('linkfilepoll', 'Link File Poll'), ('votepoll', 'Vote poll'), ('challenge', 'Challenge'), ('election', 'Election')], max_length=256)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('has_tags_flag', models.BooleanField(blank=True, default=False)),
                ('allow_multiple_tags_flag', models.BooleanField(blank=True, default=False)),
                ('members_can_add_options', models.BooleanField(default=False)),
                ('quorum', models.IntegerField(default=51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('approval_minimum', models.PositiveIntegerField(default=51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('finalization_period', models.PositiveIntegerField(default=3, help_text='Finalization period in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('active', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decidable', to='group.groupuser')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecidableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('decidable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_options', to='decidables.decidable')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDecidableAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
                ('decidable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_decidable_access', to='decidables.decidable')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_decidable_access', to='group.group')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDecidableOptionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
                ('decidable_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_decidable_option_access', to='decidables.decidableoption')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_decidable_option_access', to='group.group')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('decidables', models.ManyToManyField(blank=True, related_name='options', through='decidables.DecidableOption', to='decidables.decidable')),
                ('root_decidable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendent_options', to='decidables.decidable')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupUserDecidableVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
                ('group_decidable_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_decidable_vote', to='decidables.groupdecidableaccess')),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_decidable_vote', to='group.groupuser')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupUserDecidableOptionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.IntegerField(default=0)),
                ('group_decidable_option_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_decidable_option_vote', to='decidables.groupdecidableoptionaccess')),
                ('group_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_user_decidable_option_vote', to='group.groupuser')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='groupdecidableoptionaccess',
            name='voters',
            field=models.ManyToManyField(through='decidables.GroupUserDecidableOptionVote', to='group.groupuser'),
        ),
        migrations.AddField(
            model_name='groupdecidableaccess',
            name='voters',
            field=models.ManyToManyField(through='decidables.GroupUserDecidableVote', to='group.groupuser'),
        ),
        migrations.AddField(
            model_name='decidableoption',
            name='groups',
            field=models.ManyToManyField(related_name='decidable_options', through='decidables.GroupDecidableOptionAccess', to='group.group'),
        ),
        migrations.AddField(
            model_name='decidableoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decidable_option', to='decidables.option'),
        ),
        migrations.AddField(
            model_name='decidable',
            name='groups',
            field=models.ManyToManyField(related_name='decidables', through='decidables.GroupDecidableAccess', to='group.group'),
        ),
        migrations.AddField(
            model_name='decidable',
            name='parent_decidable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_decidables', to='decidables.decidable'),
        ),
        migrations.AddField(
            model_name='decidable',
            name='parent_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_decidables', to='decidables.option'),
        ),
        migrations.AddField(
            model_name='decidable',
            name='primary_decidable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_decidables', to='decidables.decidable'),
        ),
        migrations.AddField(
            model_name='decidable',
            name='root_decidable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendent_decidables', to='decidables.decidable'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=16)),
                ('link', models.URLField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[flowback.decidables.validators.allowed_image_extensions])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='group.groupuser')),
                ('decidable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='decidables.decidable')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='decidables.option')),
            ],
        ),
    ]
