# Generated by Django 4.2.7 on 2024-10-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decidables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decidable',
            name='has_winners',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='decidable',
            name='num_winners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decidable',
            name='reason_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason_decidable', to='decidables.option'),
        ),
        migrations.AddField(
            model_name='decidable',
            name='voting_type',
            field=models.CharField(choices=[('score', 'Score'), ('percentage', 'Percentage'), ('approval', 'Approval'), ('number', 'Number'), ('rating', 'Rating')], default='rating', max_length=64),
        ),
        migrations.AlterField(
            model_name='decidable',
            name='decidable_type',
            field=models.CharField(choices=[('poll', 'Poll'), ('aspect', 'Aspect Poll'), ('reason', 'Reason Poll'), ('linkfile', 'Link File Poll'), ('vote', 'Vote'), ('challenge', 'Challenge'), ('election', 'Election')], max_length=256),
        ),
    ]
