# Generated by Django 4.2.7 on 2024-10-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0040_topic_topic_group_unique_topics'),
        ('decidables', '0002_decidable_has_winners_decidable_num_winners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decidable',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decidables', to='group.topic'),
        ),
    ]
