# Generated by Django 4.2.7 on 2024-12-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decidables', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdecidableaccess',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='groupdecidableoptionaccess',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
