# Generated by Django 4.2.7 on 2024-12-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decidables', '0003_decidable_long_description_option_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decidable',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
