# Generated by Django 4.2.7 on 2024-11-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decidables', '0003_decidable_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decidable',
            name='reason_option',
        ),
        migrations.AddField(
            model_name='groupdecidableoptionaccess',
            name='approval',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='groupdecidableoptionaccess',
            name='quorum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='link',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
