# Generated by Django 4.2.7 on 2024-12-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_groupuser_group_alter_groupuser_user'),
        ('decidables', '0003_alter_groupdecidableaccess_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oprions', to='group.groupuser'),
        ),
        migrations.AlterField(
            model_name='decidable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decidables', to='group.groupuser'),
        ),
    ]
