# Generated by Django 4.2.7 on 2024-12-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decidables', '0004_alter_decidable_title_alter_option_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decidable',
            name='description',
            field=models.TextField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='decidable',
            name='long_description',
            field=models.TextField(blank=True, default='', max_length=1600),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='option',
            name='long_description',
            field=models.TextField(blank=True, default='', max_length=1600),
        ),
    ]
