# Generated by Django 4.2.7 on 2024-12-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decidables', '0004_option_created_by_alter_decidable_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='decidable',
            name='closes_on_end_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decidable',
            name='closes_on_finalization_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupdecidableaccess',
            name='snapshots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='groupdecidableaccess',
            name='state',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='not_started', max_length=32),
        ),
        migrations.AddField(
            model_name='groupdecidableaccess',
            name='won_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='groupdecidableoptionaccess',
            name='passed_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupdecidableoptionaccess',
            name='passed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdecidableoptionaccess',
            name='winner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='decidable',
            name='state',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='not_started', max_length=32),
        ),
    ]
