# Generated by Django 4.2.7 on 2024-12-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decidables', '0005_alter_decidable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decidable',
            name='description',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
