# Generated by Django 4.2.7 on 2024-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_long_description_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(max_length=120, unique=True),
        ),
    ]
