# Generated by Django 4.2.7 on 2024-06-05 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0030_alter_group_direct_join_alter_group_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="default_approval_minimum",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum approval percentage required for the poll to pass",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="default_finalization_period",
            field=models.DurationField(
                blank=True,
                help_text="Time period after the poll has ended before the result is finalized",
                null=True,
            ),
        ),
    ]
