# Generated by Django 4.2.7 on 2024-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0032_group_blockchain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermissions',
            name='invite_user',
            field=models.BooleanField(default=True),
        ),
    ]
