# Generated by Django 4.2.7 on 2024-07-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0033_alter_grouppermissions_invite_user'),
        ('group', '0033_groupthread_attachments'),
    ]

    operations = [
    ]
