# Generated by Django 4.2.7 on 2024-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0034_merge_20240703_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuserinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
