# Generated by Django 4.2.7 on 2024-08-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0035_groupuserinvite_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuserinvite',
            unique_together=set(),
        ),
    ]
