# Generated by Django 4.2.7 on 2024-09-08 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0036_alter_groupuserinvite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default_approval_minimum',
            field=models.PositiveIntegerField(default=51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='group',
            name='default_finalization_period',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
