# Generated by Django 4.2.7 on 2024-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0038_alter_group_default_quorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_hub_group',
            field=models.BooleanField(default=False),
        ),
    ]
