# Generated by Django 4.2.7 on 2024-11-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_messagechannelparticipant_active'),
        ('group', '0041_groupuserinvite_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.messagechannel'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='chat_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.messagechannelparticipant'),
        ),
    ]
