# Generated by Django 4.2.7 on 2024-11-27 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decidables', '0002_initial'),
        ('group', '0001_initial'),
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channelparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_channel_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='decidable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_channel', to='decidables.decidable'),
        ),
        migrations.AddField(
            model_name='channel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_channels', to='group.group'),
        ),
        migrations.AddField(
            model_name='channel',
            name='option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_channel', to='decidables.option'),
        ),
        migrations.AddField(
            model_name='channel',
            name='participants',
            field=models.ManyToManyField(related_name='feed_channels', through='feed.ChannelParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_channel', to='group.topic'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feed.message'),
        ),
        migrations.AddConstraint(
            model_name='channelparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='user_joins_chat_once'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False), ('topic__isnull', True)), fields=('group',), name='one_chat_per_group'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='channel',
            trigger=pgtrigger.compiler.Trigger(name='no_topic_without_group', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NEW."group_id" IS NULL AND NEW."topic_id" IS NOT NULL)', func="RAISE EXCEPTION 'pgtrigger: Cannot insert or update rows from % table', TG_TABLE_NAME;", hash='2aa41a8770f0b0c5043ab1ebdc54e309cc88fecb', operation='INSERT OR UPDATE', pgid='pgtrigger_no_topic_without_group_c0548', table='feed_channel', when='BEFORE')),
        ),
    ]
