# Generated by Django 4.2.7 on 2024-10-31 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='channel_participant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feed_messages', to='feed.channelparticipant'),
            preserve_default=False,
        ),
    ]
