# Generated by Django 4.2.7 on 2024-12-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feed.message', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='message',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_by', to='feed.message'),
        ),
        migrations.AddField(
            model_name='channelparticipant',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_channel_participants', to='feed.channel'),
        ),
        migrations.AddField(
            model_name='channelparticipant',
            name='group_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_channel_participants', to='group.groupuser'),
        ),
        migrations.AddField(
            model_name='channel',
            name='participants',
            field=models.ManyToManyField(related_name='feed_channels', through='feed.ChannelParticipant', to='group.groupuser'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feed.message'),
        ),
    ]
