# Generated by Django 4.2.7 on 2024-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_message_channel_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelparticipant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
