# Generated by Django 4.2.7 on 2024-11-27 07:51

from django.db import migrations, models
import django.db.models.deletion
import flowback.decidables.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_channelparticipant_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=16)),
                ('link', models.CharField(blank=True, default='', max_length=512)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[flowback.decidables.validators.allowed_image_extensions])),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feed.message')),
            ],
        ),
    ]
