# Generated by Django 4.2.7 on 2024-11-27 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('origin_type', models.CharField(max_length=255)),
                ('origin_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KanbanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.IntegerField(choices=[(1, 'backlog'), (2, 'chosen_for_execution'), (3, 'in_progress'), (4, 'evaluation'), (5, 'finished')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KanbanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_subscription_kanban', to='kanban.kanban')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_subscription_target', to='kanban.kanban')),
            ],
        ),
    ]
