# Generated by Django 4.2.7 on 2024-12-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanentry',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_entry_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbanentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_entry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbanentry',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.kanban'),
        ),
        migrations.AlterUniqueTogether(
            name='kanban',
            unique_together={('origin_type', 'origin_id')},
        ),
        migrations.AlterUniqueTogether(
            name='kanbansubscription',
            unique_together={('kanban', 'target')},
        ),
    ]
