# Generated by Django 4.2.7 on 2024-12-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefilecollection',
            name='file_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filecollection'),
        ),
    ]
